[package]
name = "perna-mix-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8"
axum = "0.7"
serenity = "0.12"
tokio = { version = "1.38.0", features = ["full"] }
shuttle-runtime = "0.48.0"
shuttle-axum = "0.48.0"
